name: craiggross
favicon: null
layout_spectrum: 0.39773
typography_spectrum: 0.775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe9c0'
    - '#a59284'
    - '#4e443a'
    - '#0f1014'
    - '#f92a4f'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
