name: craiggross
favicon: null
layout_spectrum: 0.19657
typography_spectrum: 0.46674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050606'
    - '#8c8c8c'
    - '#9d287e'
    - '#58c5cd'
  brandStrength: 0.4375
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
