name: craiggross
favicon: null
layout_spectrum: 0.39773
typography_spectrum: 0.775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99927d'
    - '#716961'
    - '#2f312f'
    - '#c1c1b1'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
